server:
  port: 8899
  servlet:
    context-path: /wx

# 百度请求api 管理
baidu:
  appid: 35695204 # 这儿配置你的 appid
  apikey: EVqNUsQzad5RGMz8f0nlkuar # 这儿配置你的 appkey
  secretkey: tli24qu2ONTWVR4TpbO0GxUXdvSKMd9A # 这儿配置你的 secretkey

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/garbagesort?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root  # 配置数据库用户
    password: 1  # 配置数据库密码
#    url: jdbc:mysql://localhost:3306/garbagesort?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
#    username: root  # 配置数据库用户
#    password: root  # 配置数据库密码
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.lxsir.uniapp.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true

# 文件路径管理
upload:
  image:
#    path: /opt/myservice/filepath/image/
#    path: /Users/luoxiang/testpath/image/    # linux or mac
    path: E:/testpath/image/                 # windows
  record:
#    path: /opt/myservice/filepath/record/
#    path: /Users/luoxiang/testpath/record/   # linux or mac
    path: E:/testpath/record/   # windows
  excel:
#    path: /opt/myservice/filepath/excel/
    path: E:/testpath/excel/


